# Generated by Django 5.0.3 on 2024-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_post_content_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
